


services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
      - NEXT_PUBLIC_GOOGLE_API_KEY=${GOOGLE_API_KEY}
    # volumes:
    # - .:/app
    # - /app/node_modules
    command: npm start