
version: '3.8'

services:
  backend:
    build:
      context: ./shopper_backend  # Ajuste o caminho para o diretório onde o Dockerfile do backend está
      dockerfile: Dockerfile
    container_name: shopper_backend
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MONGO_URI=mongodb://mongo:27017/shopper-rides
      - FRONTEND_URL=http://localhost
    depends_on:
      - mongo
    networks:
      - shopper-net

  frontend:
    build:
      context: ./shopper_frontend_next  # Ajuste o caminho para o diretório onde o Dockerfile do frontend está
      args:
        NEXT_PUBLIC_GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      dockerfile: Dockerfile
    container_name: shopper_frontend
    ports:
      - "80:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080/api  
      - NEXT_PUBLIC_GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - backend
    networks:
      - shopper-net
    command: npm start  

  mongo:
    image: mongo
    container_name: shopper_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - shopper-net

volumes:
  mongo-data: {}

networks:
  shopper-net:
    driver: bridge  # Criação de uma rede personalizada para comunicação entre os containers
